addons:
apt:
packages:
     - lynx
language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "meenaanand-github"
    token:
      secure: 498232f43d6da08733d32002266f098925f1403c

sudo: true 
before_install:
  - chmod +x mvnw

script: "mvn test && mvn verify"

after_success:
       - if [ -f /home/travis/build/kirudiha/country-springboot-ajax/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/kirudiha/country-springboot-ajax/app/build/outputs/lint-results-debug.html; fi



